language: ruby

services:
  - docker

env:
  global:
    - DOCKER_REPOSITORY=$DOCKER_USERNAME/tutor

rvm:
  - 2.5

before_install: gem install bundler

before_deploy: docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD

deploy:
  provider: script
  script: ./.travis/dockerhub
  on:
    branch: master