development:
  secret_key_base: test
  email_sender: no-reply@in.tum.de
  email_sender_full: Tutor Tool <no-reply@in.tum.de>
 
test:
  secret_key_base: test
  email_sender: no-reply@in.tum.de
  email_sender_full: Tutor Tool <no-reply@in.tum.de>
 
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  email_sender: <%= ENV["EMAIL_SENDER"] %>
  email_sender_full: <%= ENV["EMAIL_SENDER_FULL"] %>
